title: "sdxl_lora_container"
description: "Python environment built with Docker Compose"
baseurl: "/sdxl_lora_container"
url: "https://europanite.github.io"
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
highlighter: rouge
